### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by Mark2000** [AVSLab/bsk_rl#115]
@LorenzzoQM and I were discussing that it would be nice to have a logo for the package to use in documentation and presentations. Perhaps a robotic looking version of the Basilisk logo? Maybe something different on the shield that is more RL related? @schaubh, do you have the vector graphics file of the basilisk logo somewhere?

**Comment by schaubh** [comment]
Let me look.  I know I have PDF version.  I might have the OmniGraffle file.
