### ISSUE TITLE
[Windows ERROR] ImportError: DLL load failed while importing _spacecraft: The specified module could not be found！！！

### ISSUE THREAD

**Issue by xiaoJ136** [AVSLab/bsk_rl#143]
When I execute python scenarioBasicOrbit.py, it shows "ImportError: DLL load failed while importing _spacecraft: The specified module could not be found" error, I do not know how to modify this error, please help me, this is very important to me! Thanks!

```
(.venv) (bsk_drl) PS D:\option\new_Basilisk\basilisk\examples> python scenarioBasicOrbit.py
Traceback (most recent call last):
  File "D:\option\new_Basilisk\basilisk\examples\scenarioBasicOrbit.py", line 219, in <module>
    from Basilisk.simulation import spacecraft
  File "d:\option\new_basilisk\basilisk\dist3\Basilisk\simulation\spacecraft.py", line 15, in <module>
    from . import _spacecraft
ImportError: DLL load failed while importing _spacecraft: 找不到指定的模块。
```
Here is some additional information I can provide: I found the file "_spacecraft.pyd" in the directory "D:\Option\new_Basilisk\basilisk\dist3\Basilisk\simulation", also in the same directory I found the file "spacecraft.py", I opened the "spacecraft.py" using notepad++ and found the following error location:

```
from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
from . import _spacecraft
else:
import _spacecraft
```
Above is some of the information I provided that may help solve the problem, if you need more information, please let me know, I will provide the required information in the first place to solve the problem.
Thank you very much.

**Version (please complete the following information):**
 - Python: [e.g. 3.8]
-  Basilisk: [e.g. 2.3.0]
 - Platform: [e.g. Win10]

**Comment by Mark2000** [comment]
This is an issue with your Basilisk installation. Your version of python is likely too old for Basilisk and definitely too old for BSK-RL. Closing as this duplicates https://github.com/AVSLab/basilisk/issues/711
