### ISSUE TITLE
Issue in running example python files

### ISSUE THREAD

**Issue by Rishoban** [AVSLab/bsk_rl#145]
I successfully installed bsk_rl in my computer and successfully ran the example test scripts which is in tests/examples folder. But when i tried to run example python files which is located in bsk_rl/examples/general_satellite_tasking then it showed error as "At least one SPK file needs to be loaded by SPKLEF before beginning a search"

when i tried to execute following command
python single_sat.py
I got this response
![BSKIssue](https://github.com/AVSLab/bsk_rl/assets/28992337/5ced121d-b93d-45c8-8709-c0ea447587a6)

Can you guide me to resolve this interruption? 

Version 
 - Python: 3.10.12
 -  Basilisk: 2.3.5
 - Platform: Ubuntu 22.04 LTS

**Comment by Mark2000** [comment]
See here: https://avslab.github.io/bsk_rl/install.html#spice-errors

As an aside, I recommend pulling the `refactor/v1_0_0` branch and using that until we merge it into `develop` (soon). Docs are currently being build from that branch, and it has a number of usability improvements and better example scripts.
