### ISSUE TITLE
Public-facing documentation

### ISSUE THREAD

**Issue by Mark2000** [AVSLab/bsk_rl#17]
Goal: set up Sphinx docs for the repo

- [X] Use a basilisk docs-like style
- [X] Figure out best deployment strategy (support releases #14 when we start doing that) and location (GitHub? Dr. Schaub's website?). More automated = better
- [X] Primary scope is generalized environment (`bsk_rl/envs/general_satellite_tasking`). Should be optimized for this (e.g. ingest Python type hints, which may make #78 unnecessary). Since other envs are going to be wrapped into the general env (#16), documentation is less important for them; instead consider a good way of documenting some baseline environments (which may include an associated refactor of where those examples should be)
- [ ] The examples directory should be handled like examples in basilisk andother repos (rich formatted walkthrough of the code). 
- [ ] Make changelong page
- [ ] Identify pages that need content written (home pages, examples, etc.)
- [x] Make bsk setters not private so that configs are documented, preferably expose defaults. Maybe rework system to have defaults in constructor and only decorate with names of fields?

If #79 would greatly change configuration of documentation, maybe we should do it first?

**Comment by johnowagon** [comment]
I noticed many of the reStructuredText style docstrings that are currently in the repo contain syntax errors. There should be a newline after the summary section of the docstring. Im thinking this can be easily done using `sed` to change the docstrings using regex, thoughts on this approach?

**Comment by Mark2000** [comment]
Sounds like a good plan. Would be nice to have a way of automatically checking docstring formatting, not sure if such a tool exists
