### ISSUE TITLE
basilisk_env

### ISSUE THREAD

**Issue by TzuRen** [AVSLab/bsk_rl#5]
Will you upload the basilisk_env: A Basilisk-based Astrodynamics Reinforcement Learning Problems Package,
and some reinforcement learning method experiments?
![image](https://github.com/AVSLab/bsk_rl/assets/28235121/769dd6fd-4229-46f7-9f08-15e7437e0c44)

**Comment by Mark2000** [comment]
We're in the process of refactoring that code and then we'll port over from BitBucket, should expect an initial commit with the environments by the end of the month if not sooner.

**Comment by Mark2000** [comment]
@TzuRen FYI, the initial commit was just pushed to develop
