### ISSUE TITLE
Error setting up bsk_rl environment using setup.py

### ISSUE THREAD

**Issue by LorenzzoQM** [AVSLab/bsk_rl#51]
**Describe the bug**
Issues when trying to setup the environment through setup.py (pip install .) due to errors to install pyfftw as part of the requirements for chebpy. We believe this happens only on Apple M2 chip.

A workaround is to set the option "--no-deps" for chebpy in the setup.py file. 

**Expected behavior**
No errors when using setup.py.

**Version (please complete the following information):**
 - Python: [3.11.4]
-  Basilisk: [2.2.1]
 - Platform: [MacOS 13.5.1 with Apple M2 Pro chip]

**Comment by Mark2000** [comment]
Opened an issue in the chebpy repo, though given that conda installs (which probably work) are preferred over pip installs for that package, it may not be resolved. Will see if any other maintainers over there have an opinion: https://github.com/chebpy/chebpy/issues/70

**Comment by Mark2000** [comment]
Since this isn't being resolved by pyfftw/chebpy, @LorenzzoQM will have the `--no-deps` flag be added if the system is a arm silicon Mac.

**Comment by Yume27** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyfftw
Successfully built chebpy
Failed to build pyfftw
ERROR: Could not build wheels for pyfftw, which is required to install pyproject.toml-based projects
