### ISSUE TITLE
data_storage_valid check killing simulation when storage if full

### ISSUE THREAD

**Issue by LorenzzoQM** [AVSLab/bsk_rl#72]
Satellite data_storage_valid check killing the simulation (failed data_storage_valid check) when data buffer is equal to maximum storage capacity due to numerical rounding error (storage level slightly above storage capacity).

**Version (please complete the following information):**
 - Python: [3.11.5]
-  Basilisk: [2.2.1]
 - Platform: [MacOS 13.5.2]

**Comment by Mark2000** [comment]
@LorenzzoQM reopening this since I think the behavior should be to fail if the buffer is approximately full when `storageUnitValidCheck`. Didn't catch that on the PR. Should be something like:
```
    def data_storage_valid(self) -> bool:
        """Check that the buffer has not run out of space."""
        storage_check = self.storageUnitValidCheck
        if storage_check:
            return self.storage_level < self.storageUnit.storageCapacity and not np.isclose(
                self.storage_level, self.storageUnit.storageCapacity
            )
        else:
            return True
```
with `and not` replacing what used to be `or`

**Comment by Mark2000** [comment]
@LorenzzoQM can this issue be closed with your bsk changes to make storage an int?

**Comment by LorenzzoQM** [comment]
@Mark2000 yes! This issue can be closed now that the storage unit uses int.

**Comment by LorenzzoQM** [comment]
Basilisk now uses [int variable type for storage](https://github.com/AVSLab/basilisk/pull/507), avoiding numerical rounding errors and fixing this issue.
