### ISSUE TITLE
Convert docstrings to Sphinx style

### ISSUE THREAD

**Issue by Mark2000** [AVSLab/bsk_rl#78]
Part of #17 (unless unnecessary, see linked issue for more details)

**Comment by johnowagon** [comment]
Since this is a large PR im going to make this separate from #17 and create a new branch for it. Instead of Converting them all to sphinx style I think it makes more sense to use the current style (some numpy, some google, some sphinx) and utilize `sphinx.ext.napoleon` to handle them all.

**Comment by Mark2000** [comment]
Nice, looks like that can also handle the type annotations: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#type-annotations
